services:
    keycloak_core:
        image: quay.io/keycloak/keycloak:23.0.7
        container_name: keycloak_core
        environment:
            KC_DB: postgres
            KC_DB_URL: ${KEYCLOAK_DB_URL}
            KC_DB_USERNAME: ${KC_DB_USERNAME}
            KC_DB_PASSWORD: ${KC_DB_PASSWORD}

            KC_HOSTNAME: localhost
            KC_HOSTNAME_PORT: 8080
            KC_HOSTNAME_STRICT: false
            KC_HOSTNAME_STRICT_HTTPS: false

            KC_LOG_LEVEL: info
            KC_METRICS_ENABLED: true
            KC_HEALTH_ENABLED: true
            KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
            KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
        command: start-dev
        depends_on:
            - keycloakdb
        ports:
            - 8080:8080

    keycloakdb:
        image: postgres:15
        container_name: keycloakdb
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - 5432:5432

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - 5050:80
        depends_on:
            - keycloakdb

    go-auth-app:
        build: .
        container_name: go-auth-app
        ports:
            - 8081:8081
        depends_on:
            - keycloak_core
        environment:
            KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
            KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
            KEYCLOAK_TOKEN_URL: ${KEYCLOAK_TOKEN_URL}
            # Set MONGO_URI to your Atlas connection string.
            MONGO_URI: ${MONGO_URI}
        command: ./go-auth-app

volumes:
    postgres_data:
